---
title: "data"
author: "Hanjuan Zhang"
date: "4/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('magrittr')
library('mi')
library(ggplot2)
library(plyr)
library(ggridges)
library(forcats)
library(dplyr)
```

## loading data
```{r}
df_2019 <- read.csv(file = 'dcpc_2019_indlevel_public-csv.csv')[ ,c('paypref_b1', 'age')]
df_2018 <- read.csv(file = 'dcpc_2018_indlevel-csv.csv')[ ,c('paypref_b1', 'age')]
df_2017 <- read.csv(file = 'dcpc_2017_indlevel-csv.csv')[ ,c('paypref_b1', 'age')]
df_2016 <- read.csv(file = 'dcpc-2016-public-data-csv.csv')[ ,c('id','paypref_b1', 'age')]
df_2015 <- read.csv(file = 'dcpc-2015-public-data-csv.csv')[ ,c('id','paypref_b1', 'age')]
```

```{r}
df_2016 <- distinct(df_2016, id, .keep_all = TRUE)
df_2015 <- distinct(df_2015, id, .keep_all = TRUE)
#head(df_2016)
```

### washing paypref
```{r}
df_2019$paypref_b1 <- mapvalues(df_2019$paypref_b1,
                           from = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                           to = c("Cash", "Check", "Credit card", "Debit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Money order", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method"))

df_2019$paypref_b1 <- factor(df_2019$paypref_b1, levels = rev(c("Cash", "Check", "Money order", "Debit card", "Credit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method")))

df_2018$paypref_b1 <- mapvalues(df_2018$paypref_b1,
                           from = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                           to = c("Cash", "Check", "Credit card", "Debit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Money order", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method"))

df_2018$paypref_b1 <- factor(df_2018$paypref_b1, levels = rev(c("Cash", "Check", "Money order", "Debit card", "Credit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method")))

df_2017$paypref_b1 <- mapvalues(df_2017$paypref_b1,
                           from = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                           to = c("Cash", "Check", "Credit card", "Debit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Money order", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method"))

df_2017$paypref_b1 <- factor(df_2017$paypref_b1, levels = rev(c("Cash", "Check", "Money order", "Debit card", "Credit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method")))

df_2016$paypref_b1 <- mapvalues(df_2016$paypref_b1,
                           from = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                           to = c("Cash", "Check", "Credit card", "Debit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Money order", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method"))

df_2016$paypref_b1 <- factor(df_2016$paypref_b1, levels = rev(c("Cash", "Check", "Money order", "Debit card", "Credit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method")))


df_2015$paypref_b1 <- mapvalues(df_2015$paypref_b1,
                           from = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                           to = c("Cash", "Check", "Credit card", "Debit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Money order", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method"))

df_2015$paypref_b1 <- factor(df_2015$paypref_b1, levels = rev(c("Cash", "Check", "Money order", "Debit card", "Credit card", "Prepaid/gift/EBT card", "Bank account number payment", "Online banking bill payment", "Traveler’s check", "PayPal", "Account-to-account transfer", "Mobile phone payment", "Other payment method")))

```
```{r}
df_2018 <- df_2018[rowSums(is.na(df_2018)) == 0,]
df_2017 <- df_2017[rowSums(is.na(df_2017)) == 0,]
df_2016 <- df_2016[rowSums(is.na(df_2016)) == 0,]
df_2016 <- select(df_2016,"paypref_b1","age")
df_2015 <- df_2015[rowSums(is.na(df_2015)) == 0,]
df_2015 <- select(df_2015,"paypref_b1","age")
```


```{r}
colSums(is.na(df_2015)) %>%  
  sort(decreasing = TRUE)

df4 <- df_2018[rowSums(is.na(df_2018)) > 0,]
str(df4)

#new_testdf1 <- df_2018[is.na(testdf$income_hh),]
#str(new_testdf1)
#x <- missing_data.frame(new_testdf[])
#image(x)
#x <- missing_data.frame(new_testdf1[])
#image(x)

```

### age vs paypref

```{r}
df <- df_2019
df$age <- cut(df$age, breaks = c(18, 25, 35, 45, 55, 65 , 109), include.lowest = TRUE)
df$age <- factor(df$age, levels = rev(levels(df$age)))
str(df)
df <- df %>% count(paypref_b1, age)
ggplot(df, aes(y=age, x=n, fill=paypref_b1)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3")


df <- df_2018
df$age <- cut(df$age, breaks = c(18, 25, 35, 45, 55, 65 , 109), include.lowest = TRUE)
df$age <- factor(df$age, levels = rev(levels(df$age)))
str(df)
df <- df %>% count(paypref_b1, age)
ggplot(df, aes(y=age, x=n, fill=paypref_b1)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3")


df <- df_2017
df$age <- cut(df$age, breaks = c(18, 25, 35, 45, 55, 65 , 109), include.lowest = TRUE)
df$age <- factor(df$age, levels = rev(levels(df$age)))
str(df)
df <- df %>% count(paypref_b1, age)
ggplot(df, aes(y=age, x=n, fill=paypref_b1)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3")

df <- df_2016
df$age <- cut(df$age, breaks = c(18, 25, 35, 45, 55, 65 , 109), include.lowest = TRUE)
df$age <- factor(df$age, levels = rev(levels(df$age)))
str(df)
df <- df %>% count(paypref_b1, age)
ggplot(df, aes(y=age, x=n, fill=paypref_b1)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3")

df <- df_2015
df$age <- cut(df$age, breaks = c(18, 25, 35, 45, 55, 65 , 109), include.lowest = TRUE)
df$age <- factor(df$age, levels = rev(levels(df$age)))
str(df)
df <- df %>% count(paypref_b1, age)
ggplot(df, aes(y=age, x=n, fill=paypref_b1)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3")
```
```{r}
df_2019$year <- as.factor("2019") 
head(df_2019)
df_2018$year <- as.factor("2018") 
head(df_2018)
df_2017$year <- as.factor("2017") 
head(df_2017)
df_2016$year <- as.factor("2016") 
head(df_2016)
df_2015$year <- as.factor("2015") 
head(df_2015)
```
```{r}
df <- rbind(df_2019,df_2018,df_2017,df_2016,df_2015)
str(df)
head(df)
colSums(is.na(df)) %>%  
  sort(decreasing = TRUE)
df$age <- cut(df$age, breaks = c(18, 25, 35, 45, 55, 65, max(df$age)), include.lowest = TRUE)
df$age <- factor(df$age, levels = rev(levels(df$age)))
```

```{r}
df1 <- df[df["paypref_b1"] == "Cash",]
head(df1)
df1 <- df1 %>% count(year, age)
ggplot(df1, aes(y=year, x=n, fill=age)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3") 

df1 <- df[df["paypref_b1"] == "Check",]
head(df1)
df1 <- df1 %>% count(year, age)
ggplot(df1, aes(y=year, x=n, fill=age)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3") 

df2 <- df[df["age"] == "[18,25]",]
head(df2)
df2 <- df2 %>% count(year, paypref_b1)
ggplot(df2, aes(y=year, x=n, fill=paypref_b1)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3")

df3 <- df[df["age"] == "(65,109]",]
head(df3)
df3 <- df3 %>% count(year, paypref_b1)
ggplot(df3, aes(y=year, x=n, fill=paypref_b1)) + 
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Set3")
```



```{r} 
new_df <- tidyr::pivot_wider(data = df3, id_cols = c(year), names_from = paypref_b1, values_from = n, values_fn = sum)
new_df[is.na(new_df)] = 0
new_df
```

```{r}
write.csv(new_df,"age_65-109.csv", row.names = FALSE)
```
